apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: php-ingress
  namespace: prakai-project-01
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # This ensures the app receives the request correctly even with the sub-path
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: project.cpe.rmuti.ac.th  # <--- Updated Domain
    http:
      paths:
      - path: /prakai-project-0/
        pathType: Prefix
        backend:
          service:
            name: php-service
            port:
              number: 80
