apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: php-ingress
  namespace: prakai-project-01
  annotations:
    # Keep the rewrite but remove the ingress.class annotation
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx # <--- Add this line instead of the annotation
  rules:
  - host: project.cpe.rmuti.ac.th
    http:
      paths:
      - path: /prakai-project-0/
        pathType: Prefix
        backend:
          service:
            name: php-service
            port:
              number: 80
